version: '2'
services:
  website:
    build: docker/website-dev
    command: npm run start
    ports:
     - "3000:3000"
    volumes:
      - ./website:/opt/website
      - frontend_deps:/opt/frontend/node_modules
      - website_dist:/opt/website/dist

  backend:
    build: docker/backend-dev
    command: mix phoenix.server
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/opt/backend
      - backend_deps:/opt/backend/deps
      - backend_build:/opt/backend/_build
    links:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  frontend_deps:
    driver: local
  website_dist:
    driver: local
  pg_data:
    driver: local
  backend_deps:
    driver: local
  backend_build:
    driver: local
